// EDIT THIS FILE to update the agenda.
// date: YYYY-MM-DD. Leave reviewer or owner as '' when it is empty.
// area: used by the Área filter. format: normally "Programada" or "No hay sesión".
const sessions = [
  { date:'2026-09-18', title:'Industria: Prepresina', area:'Industria', owner:'Inés Baptista', reviewer:'', format:'Programada' },
  { date:'2026-09-22', title:'Más allá del suero fisiológico: papel real de otros fluidos de resucitación', area:'Servicio', owner:'María Hidalgo (R2)', reviewer:'Isaías Martín', format:'Programada' },
  { date:'2026-09-23', title:'Área de Salud de Críticos', area:'Gestión', owner:'Marta González (Mérida)', reviewer:'Mario Chico', format:'Programada' },
  { date:'2026-09-24', title:'Ácido tranexámico: dosis, administración e indicaciones', area:'Servicio', owner:'Karina Fontalvo (Valencia)', reviewer:'Adrián Marcos', format:'Programada' },
  { date:'2026-09-29', title:'Infarto perioperatorio tras cirugía cardiaca', area:'Cardiológico', owner:'Clara Vazquez (Segovia)', reviewer:'Rosana Ashbaugh', format:'Programada' },
  { date:'2026-09-30', title:'Abstracts ESICM', area:'Congreso', owner:'R3, R4, R5', reviewer:'', format:'Programada' },
  { date:'2026-10-01', title:'Abstracts ESICM', area:'Congreso', owner:'R3, R4, R5', reviewer:'', format:'Programada' },
  { date:'2026-10-06', title:'Abstracts ESICM', area:'Congreso', owner:'Adjuntos', reviewer:'', format:'Programada' },
  { date:'2026-10-07', title:'No hay sesión', area:'', owner:'', reviewer:'', format:'No hay sesión' },
  { date:'2026-10-08', title:'¿Hay que anticoagular la fibrilación auricular en la UCI?', area:'Servicio', owner:'Elisa Carmona (Cardio)', reviewer:'Amanda Lesmes', format:'Programada' },
  { date:'2026-10-13', title:'No hay sesión (ESICM)', area:'ESICM', owner:'', reviewer:'', format:'No hay sesión' },
  { date:'2026-10-14', title:'No hay sesión (ESICM)', area:'ESICM', owner:'', reviewer:'', format:'No hay sesión' },
  { date:'2026-10-15', title:'Trauma cerebral penetrante', area:'Trauma', owner:'Jorge Guridi (R3)', reviewer:'Paco Delgado', format:'Programada' },
  { date:'2026-10-21', title:'Implicaciones en la definición SDRA del 2024: utilidad o confusión?', area:'Respiratorio', owner:'Álvaro González de Vega (R3)', reviewer:'Ignacio Sáez', format:'Programada' },
  { date:'2026-10-22', title:'Nueva definición del infarto agudo de miocardio', area:'Cardiológico', owner:'Eduardo Aguirre (R4)', reviewer:'Alejandro Moneo', format:'Programada' },
  { date:'2026-10-27', title:'Fístula broncoalveolar traumática', area:'Trauma', owner:'Julia Guerra (Fuenlabrada)', reviewer:'Jesús Barea', format:'Programada' },
  { date:'2026-10-28', title:'Trauma intestinal o mesentérico', area:'Trauma', owner:'Juan Carlos Rivero (Gómez Ulla)', reviewer:'Rubén Cillero', format:'Programada' },
  { date:'2026-10-29', title:'Retirada de dispositivos tras cirugía cardiaca: cables de marcapasos, tubos de tórax', area:'Cardiológico', owner:'Marta Barba (Getafe)', reviewer:'Nerea Quílez', format:'Programada' },
  { date:'2026-11-03', title:'¿En el trauma grave, extubación o traqueostomía precoz?', area:'Trauma', owner:'María Valero (Logroño)', reviewer:'Pablo Risco', format:'Programada' },
  { date:'2026-11-04', title:'Corticoides en neumonía del paciente crítico', area:'Servicio', owner:'Diego Revilla (Interna)', reviewer:'Silvia Chacón', format:'Programada' },
  { date:'2026-11-05', title:'Fisiopatología: actualización doctrina Monro-Kellie 4.0', area:'Neurocrítico', owner:'Nerea San Martín', reviewer:'Alejandro Caballo', format:'Programada' },
  { date:'2026-11-10', title:'Sesión Estudio INTUPROS', area:'Estudio', owner:'Rosana Ashbaugh', reviewer:'', format:'Programada' },
  { date:'2026-11-11', title:'Impella: a propósito de un caso', area:'Cardiológico', owner:'Jose Ángel García', reviewer:'Ivan Mataix', format:'Programada' },
  { date:'2026-11-12', title:'Láctico elevado ¿siempre significa hipoxia?', area:'Servicio', owner:'Mario Peinado', reviewer:'Gonzalo Leoz', format:'Programada' },
  { date:'2026-11-17', title:'Presentación estudios SOMIAMA 2026', area:'Congreso', owner:'Residentes', reviewer:'', format:'Programada' },
  { date:'2026-11-18', title:'Presentación estudios SOMIAMA 2026', area:'Congreso', owner:'Residentes', reviewer:'', format:'Programada' },
  { date:'2026-11-19', title:'Sedación inhalada: indicaciones y problemas', area:'Servicio', owner:'Carmen Galiano', reviewer:'Patricia Rodríguez', format:'Programada' },
  { date:'2026-11-20', title:'Industria: Rezafungina', area:'Industria', owner:'Sara (Mundipharma)', reviewer:'', format:'Programada' },
  { date:'2026-11-25', title:'Trauma (tema pendiente)', area:'Trauma', owner:'Diego Molina (P Asturias)', reviewer:'', format:'Programada', hidden:true  },
  { date:'2026-11-26', title:'Trauma (tema pendiente)', area:'Trauma', owner:'Carmen Fuentes (Cádiz)', reviewer:'', format:'Programada', hidden:true  },
  { date:'2026-12-10', title:'Protocolo depuración hepática??', area:'Hepático', owner:'Zaira Molina', reviewer:'', format:'Programada', hidden:true  },
  { date:'2026-12-11', title:'Otra sesion', area:'Servicio', owner:'Adrian Marcos', reviewer:'', format:'Programada', hidden:true  },
  ];
